### ISSUE TITLE
Method of Sending DONT\WONT can cause negotiation looping

### ISSUE THREAD

**Issue by A9G-Data-Droid** [9swampy/Telnet#31]
The default state of all options is DONT\WONT. You are only supposed to reply on state change. We only want to turn on suppress go ahead and we can't support it being off. Therefore we should ignore Don't\Won't because that is the default state.
This helps avoid loops.
See RFC1143: https://tools.ietf.org/html/rfc1143

I have a solution that I will propose in an upcoming Pull Request.

**Comment by 9swampy** [comment]
@A9G-Data-Droid  I've had the chance over the past week to catch up with some tasks and the changes you proposed caused me no issues, so while I still bow to your better knowledge of the RFCs since half as many have been using the 0.9.0 beta as the old 0.8.4 and no-ones complained that it caused any issues (quite the contrary as you're aware) could I ask you to review the merge conflict resolutions I did to rebase your code on to the head, and if all looks good for you I'll merge to master and knock the beta off.

**Comment by 9swampy** [comment]
@A9G-Data-Droid I'd already done the rebase mate; [see here](https://github.com/9swampy/Telnet/tree/release/0.9.1). If you check that out it should include all your stuff already and fixed the merge issues (hopefully correctly). Merging in to your original from the updated master would be a nightmare... but you're discovering that already...

**Comment by 9swampy** [comment]
Included in the release 0.9.1 I've just pushed to Nuget.

Any problems, shout.
